---
title: "Data Exploration"
author: "François Delavy"
date: "11/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(rio)
library(glue)
library(lubridate)
library(stringr)

subm <- rio::import("vfsg_submissions.csv") %>% 
  mutate(ProjectDate = format(lubridate::parse_date_time(`Date of project`, orders = c("my")), "%Y-%m"),
         Volunteer = as.factor(`Name of volunteer`),
         URL = ifelse(stringr::str_detect(string = URL, pattern = "http"), URL, NA),
         `Volunteer City` = ifelse(stringr::str_detect(string = `Volunteer City`, pattern = "nknown"), NA, `Volunteer City`)

         )


```

## Data

```{r}
glimpse(subm)
```

## Basic Stats

```{r}

glue("Number of observations: {dim(subm)[1]}")
glue("Number of projects: {subm$`Name of charity/Project` %>% unique() %>% length()}")
glue("Number of charity countries: {subm$`Charity Country` %>% unique() %>% length()}")
glue("Number of charity cities: {subm$`Charity City` %>% unique() %>% length()}")
glue("Number of topics: {subm$Topic %>% unique() %>% length()}")
glue("Projects range from {min(subm$ProjectDate)} to {max(subm$ProjectDate)}")
glue("Number of volunteers who participated {subm$`Name of volunteer` %>% unique() %>% length()}")
glue("Number of volunteer countries: {subm$`Volunteer Country`  %>% unique() %>% length()}")
glue("Number of volunteer cities: {subm$`Volunteer City`  %>% unique() %>% length()}")
glue("Number of unkown URLs: {subm$URL %>% is.na() %>% sum()}, that is {round(subm$URL %>% is.na() %>% sum() / subm$URL %>% is.na() %>% length() * 100, 1)}%")

```

## Basic plots

```{r}
toplot <- dplyr::count(subm, Volunteer, sort=TRUE) %>% head(20) %>% mutate(Volunteer = fct_reorder(Volunteer, n))
ggplot(toplot, aes(x = Volunteer, y = n)) +
  geom_col() + coord_flip() + theme_minimal() +
  ggtitle("Top 20 volunteers:")
```

```{r}
toplot <- subm %>% count(`Volunteer Country`, sort=TRUE)  %>% mutate(Volcount  = fct_reorder(`Volunteer Country`, n))
ggplot(toplot, aes(x = Volcount, y = n)) +
  geom_col() + coord_flip() + theme_minimal() +
  ggtitle("Volunteer's countries (not done by distinct volunteer)")
```

```{r, fig.height=18}
toplot <- subm %>% count(`Volunteer City`, sort = TRUE)  %>% mutate(Volcity  = fct_reorder(`Volunteer City`, n))
ggplot(toplot, aes(x = Volcity, y = n)) +
  geom_col() + coord_flip() + theme_minimal() +
  ggtitle("Volunteer's cities (not done by distinct volunteer)")
```


```{r}
toplot <- subm %>% count(`Charity Country`, sort=TRUE)  %>% mutate(Charcount  = fct_reorder(`Charity Country`, n))
ggplot(toplot, aes(x = Charcount, y = n)) +
  geom_col() + coord_flip() + theme_minimal() +
  ggtitle("Charity's countries (not done by distinct charity)")
```




```{r}
toplot <- subm %>% count(`Charity City`, sort=TRUE)  %>% mutate(Charcity  = fct_reorder(`Charity City`, n))
ggplot(toplot, aes(x = Charcity, y = n)) +
  geom_col() + coord_flip() + theme_minimal() +
  ggtitle("Charity's cities (not done by distinct charity)")
```





